"""phase1 operational schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 05:26:48.902767
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config_version', sa.String(length=60), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('n_sessions', sa.Integer(), nullable=False),
    sa.Column('n_events', sa.BigInteger(), nullable=True),
    sa.Column('dead_letter_events', sa.BigInteger(), nullable=True),
    sa.Column('positive_rate', sa.Float(), nullable=True),
    sa.Column('noise_source', sa.Text(), nullable=True),
    sa.Column('generation_seconds', sa.Float(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dead_letter_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_events_session_id'), 'dead_letter_events', ['session_id'], unique=False)
    op.create_table('holdout_accesses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('split_version', sa.String(length=160), nullable=False),
    sa.Column('access_no', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=80), nullable=False),
    sa.Column('git_head', sa.String(length=64), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdout_accesses_split_version'), 'holdout_accesses', ['split_version'], unique=False)
    op.create_table('labels',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('violation', sa.Boolean(), nullable=False),
    sa.Column('violation_types', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labeler', sa.Text(), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.CheckConstraint("confidence IN ('certain','probable','uncertain')", name='ck_labels_confidence'),
    sa.CheckConstraint("source IN ('simulated','mock','reviewed')", name='ck_labels_source'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('adult_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'WITHDRAWN')", name='ck_participants_status'),
    sa.CheckConstraint('adult_confirmed = true', name='ck_participants_adult'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_code'), 'participants', ['code'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('participant_id', sa.String(length=40), nullable=False),
    sa.Column('consent_version', sa.String(length=40), nullable=False),
    sa.Column('signed_name', sa.String(length=200), nullable=False),
    sa.Column('consent_recording', sa.Boolean(), nullable=False),
    sa.Column('consent_analysis', sa.Boolean(), nullable=False),
    sa.Column('consent_retention', sa.Boolean(), nullable=False),
    sa.Column('understands_withdrawal', sa.Boolean(), nullable=False),
    sa.Column('ethics_reference', sa.String(length=120), nullable=True),
    sa.Column('witnessed_by', sa.String(length=120), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('consent_recording AND consent_analysis AND consent_retention AND understands_withdrawal', name='ck_consents_all_items'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_participant_id'), 'consents', ['participant_id'], unique=False)
    op.create_table('demographics',
    sa.Column('participant_id', sa.String(length=40), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('participant_id', sa.String(length=40), nullable=True),
    sa.Column('helper_participant_id', sa.String(length=40), nullable=True),
    sa.Column('dataset_version', sa.String(length=120), nullable=True),
    sa.Column('script_id', sa.String(length=60), nullable=True),
    sa.Column('script_version', sa.String(length=20), nullable=True),
    sa.Column('is_rehearsal', sa.Boolean(), nullable=False),
    sa.Column('behavior_profile', sa.String(length=40), nullable=True),
    sa.Column('lighting', sa.String(length=16), nullable=True),
    sa.Column('webcam_class', sa.String(length=16), nullable=True),
    sa.Column('room_noise', sa.String(length=16), nullable=True),
    sa.Column('connection_stability', sa.String(length=16), nullable=True),
    sa.Column('eyewear', sa.Boolean(), nullable=True),
    sa.Column('head_covering', sa.Boolean(), nullable=True),
    sa.Column('baseline_movement', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('channels_outage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('browser', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source <> 'MOCK' OR participant_id IS NOT NULL", name='ck_sessions_mock_participant'),
    sa.CheckConstraint("source IN ('SIMULATED', 'MOCK')", name='ck_sessions_source'),
    sa.CheckConstraint("status IN ('GENERATED', 'CREATED', 'CONSENTED', 'RECORDING', 'RECORDED', 'UPLOADED', 'PROCESSING', 'ANALYZING', 'COMPLETED', 'FAILED', 'REVIEWED', 'DELETED')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['dataset_version'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['helper_participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_created', 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_dataset_version'), 'sessions', ['dataset_version'], unique=False)
    op.create_index(op.f('ix_sessions_participant_id'), 'sessions', ['participant_id'], unique=False)
    op.create_index('ix_sessions_source_status', 'sessions', ['source', 'status'], unique=False)
    op.create_table('data_splits',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('split_version', sa.String(length=160), nullable=False),
    sa.Column('split', sa.String(length=12), nullable=False),
    sa.CheckConstraint("split IN ('train', 'validation', 'calibration', 'holdout')"),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'split_version')
    )
    op.create_index(op.f('ix_data_splits_split'), 'data_splits', ['split'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_uid', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('detector', sa.String(length=80), nullable=False),
    sa.Column('detector_version', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_uid', name='uq_events_session_uid')
    )
    op.create_index('ix_events_session_channel', 'events', ['session_id', 'channel'], unique=False)
    op.create_index('ix_events_session_ts', 'events', ['session_id', 'ts_ms'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('webcam_av', 'enrollment_image')", name='ck_recordings_kind'),
    sa.CheckConstraint("status IN ('STORED', 'PURGED')", name='ck_recordings_status'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_recordings_size'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_session_id'), 'recordings', ['session_id'], unique=False)
    op.create_table('script_episodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('episode_no', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=40), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('scheduled_start_ms', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_end_ms', sa.BigInteger(), nullable=False),
    sa.Column('shown_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('completed_at_ms', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'episode_no')
    )
    op.create_index(op.f('ix_script_episodes_session_id'), 'script_episodes', ['session_id'], unique=False)
    op.create_table('session_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_status_history_session_id'), 'session_status_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_status_history_session_id'), table_name='session_status_history')
    op.drop_table('session_status_history')
    op.drop_index(op.f('ix_script_episodes_session_id'), table_name='script_episodes')
    op.drop_table('script_episodes')
    op.drop_index(op.f('ix_recordings_session_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index('ix_events_session_ts', table_name='events')
    op.drop_index('ix_events_session_channel', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_data_splits_split'), table_name='data_splits')
    op.drop_table('data_splits')
    op.drop_index('ix_sessions_source_status', table_name='sessions')
    op.drop_index(op.f('ix_sessions_participant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_dataset_version'), table_name='sessions')
    op.drop_index('ix_sessions_created', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_consents_participant_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_participants_code'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('labels')
    op.drop_index(op.f('ix_holdout_accesses_split_version'), table_name='holdout_accesses')
    op.drop_table('holdout_accesses')
    op.drop_index(op.f('ix_dead_letter_events_session_id'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
