"""Generate docs/MODEL_CARD.md (FR-42) from the stored results so every number is the measured one."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "reports" / "evaluation"
M = ROOT / "models" / "trained" / "fusion-v1.0.0"


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def main() -> None:
    meta = json.loads((M / "bundle.json").read_text())
    tr = json.loads((M / "training_results.json").read_text())
    ev = json.loads((R / "evaluation.json").read_text())
    nr = json.loads((R / "noise_robustness.json").read_text())
    h1 = json.loads((R / "holdout_access_1.json").read_text())
    h2 = json.loads((R / "holdout_access_2.json").read_text())
    v, b, t = tr["primary"]["validation"], tr["baseline"]["validation"], tr["temporal"]["validation"]
    p2 = h2["primary"]
    slices = "\n".join(
        f"| {f.replace('_', ' ')} | {s['fpr_disparity']:.2f} ({s['fpr_disparity_ci'][0]:.2f}–{s['fpr_disparity_ci'][1]:.2f}) | "
        + ", ".join(f"{lv['level']}: {pct(lv['fpr'])} (n={lv['n']})" for lv in s["levels"])
        + " |"
        for f, s in h2["slices"].items()
    )
    vslices = "\n".join(
        f"| {f.replace('_', ' ')} | {s['fpr_disparity']:.2f} ({s['fpr_disparity_ci'][0]:.2f}–{s['fpr_disparity_ci'][1]:.2f}) |"
        for f, s in ev["slices"].items()
    )
    miss = max(m["share_increased"] for m in h2["missing_channel"])
    ablation = "\n".join(f"| {a['group']} | {a['variant']} | {a['val_pr_auc']:.3f} |" for a in ev["ablations"])
    mit = ev["mitigation"]["results"]
    nrn = list(nr.values())
    card = f"""# Model card — {meta["model_version"]}

*Generated by `scripts/make_model_card.py` from the stored evaluation results.*

## What it is for

RiskFusion estimates how likely it is that an online exam session contains behaviour a **human reviewer** should look
at, and orders sessions for review. Its output is a calibrated risk, a review tier (no action / routine / human /
priority), plain-language reasons and time-bounded moments to check.

**It is not for:** deciding that anyone cheated, penalising anyone automatically, ranking people, or any use without
a trained human reviewer who looks at the evidence. Its outputs contain no verdict by design (SRS CON-5, ETH-6).

## Model

- Gradient-boosted trees (LightGBM) over {len(meta["features"])} session features from {len(set(f.split("__")[0] for f in meta["features"]))} signal families across 11 channels
  ({meta["feature_version"]}); class imbalance handled with `scale_pos_weight`.
- **Monotone constraints on every feature** (direction learned on the training split). With the missing-channel
  imputation this *guarantees* a missing channel can never raise a score (FR-30).
- {meta["calibration"]["method"].title()} calibration fitted on the dedicated calibration split.
- Operating point and tiers chosen from reviewer capacity: human review ≥ {meta["tiers"]["HUMAN_REVIEW"]:.3f}
  (3% of clean calibration sessions), priority ≥ {meta["tiers"]["PRIORITY_REVIEW"]:.3f} (0.5%), routine ≥ {meta["tiers"]["ROUTINE_REVIEW"]:.3f} (10%).
- Selected params {meta["params"]}, {meta["best_iteration"]} trees, seed {meta["seed"]}.

## Data

- **Training data is simulated** ({meta["dataset_version"]}): 5,000 sessions, 6.4% with violations, 10 behaviour profiles,
  8 nuisance factors, persistent confounders (phone on desk, background talk, writing, notifications, identity
  drift) and 35% evasive violations. Split by session and stratified: train 2,998 / validation 651 /
  calibration 601 / sealed holdout 750.
- Detector error rates are the SRS DR-3 **planning estimates made more pessimistic, not yet measured**. FR-6 code
  replaces them with rates measured on the consented mock corpus once it holds ≥ 20 analysed sessions.
- No real exam data (CON-1). No demographic attribute is a model input (ETH-4).

## Performance

| | PR-AUC | Recall at op. point | FPR | ECE |
|---|---|---|---|---|
| Rule baseline (validation) | {b["pr_auc"]:.3f} | {pct(b["recall"])} | {pct(b["fpr"])} | {b["ece"]:.3f} |
| Temporal ROCKET model (validation) | {t["pr_auc"]:.3f} | {pct(t["recall"])} | {pct(t["fpr"])} | {t["ece"]:.3f} |
| **Fusion (validation)** | **{v["pr_auc"]:.3f}** | **{pct(v["recall"])}** | **{pct(v["fpr"])}** | **{v["ece"]:.3f}** |
| Fusion, sealed holdout access 1 | {h1["primary"]["pr_auc"]:.3f} | {pct(h1["primary"]["recall"])} | {pct(h1["primary"]["fpr"])} | {h1["primary"]["ece"]:.3f} |
| **Fusion, sealed holdout (final)** | **{p2["pr_auc"]:.3f}** (95% CI {p2["pr_auc_ci"][0]:.2f}–{p2["pr_auc_ci"][1]:.2f}) | **{pct(p2["recall"])}** | **{pct(p2["fpr"])}** | **{p2["ece"]:.3f}** |

Relative PR-AUC gain over the rule baseline on validation: {100 * tr["primary"]["relative_pr_auc_gain_vs_baseline"]:.0f}% (target ≥ 15%).
Recall on evasive (subtle) violations: {pct(ev["subtle_recall"]["subtle"])} vs {pct(ev["subtle_recall"]["overt"])} on overt ones.
Time-bounded flags reach IoU ≥ 0.5 for {pct(ev["flags"]["share_iou_ge_0_5"])} of true episodes (target 70%).

## Fairness (FR-27, FR-28)

FPR disparity = highest ÷ lowest slice FPR (add-one smoothed), 95% bootstrap CI. Target < 1.3.

Validation:

| Factor | Disparity (CI) |
|---|---|
{vslices}

Final holdout:

| Factor | Disparity (CI) | FPR per level |
|---|---|---|
{slices}

**The 1.3 target is not met for every factor.** Slices are small (most under 300 sessions), so the intervals are wide
and the point estimates unstable. Mitigation tested (FR-29): {ev["mitigation"]["method"]}. It changed validation
FPR from {pct(mit["before (unweighted)"]["fpr"])} to {pct(mit["after (slice-balanced weights)"]["fpr"])} but widened lighting disparity
({mit["before (unweighted)"]["fpr_disparity_lighting"]:.2f} → {mit["after (slice-balanced weights)"]["fpr_disparity_lighting"]:.2f}), so it was not adopted.

## Robustness

- Missing channels (FR-30): the largest share of sessions whose score rose when any single channel was removed is
  {pct(miss)} on the final holdout — guaranteed by construction, not only observed.
- Detector false positives +50% (FR-31), 800 new sessions: PR-AUC {nrn[0]["pr_auc"]:.3f} → {nrn[1]["pr_auc"]:.3f},
  FPR {pct(nrn[0]["fpr"])} → {pct(nrn[1]["fpr"])}, recall {pct(nrn[0]["recall"])} → {pct(nrn[1]["recall"])}.
  Degraded detectors are caught by the drift monitor (PSI alerts) before FPR drifts unnoticed.

## Ablations (validation PR-AUC)

| Group | Variant | PR-AUC |
|---|---|---|
{ablation}

## Known limitations and risks

- Trained and evaluated on **simulated** data. Real-world performance is unknown until the mock-corpus validation
  (FR-3, FR-6) and, ultimately, a properly governed pilot.
- The heuristic speaker detector (MFCC clustering) is weak; there is no licensed liveness model, so liveness is
  always reported unavailable; gaze is a head-pose proxy.
- Clean sessions are sent to review at {pct(p2["fpr"])} on the holdout, above the 3% budget set on calibration data;
  budgets must be re-checked on real data before use.
- Poor lighting, low-quality webcams and unstable connections change error rates. Reviewers must be told this.
- InsightFace weights are licensed for non-commercial research only.

## Ethical considerations

See `docs/FINAL_REPORT.md`, section "Harms of automated proctoring". Every output must be reviewed by a person;
candidates must be able to contest outcomes; missing data never counts against a candidate.
"""
    (ROOT / "docs" / "MODEL_CARD.md").write_text(card)
    print("docs/MODEL_CARD.md written")


if __name__ == "__main__":
    main()
