"""FR-6: measure each detector's error on consented mock recordings against scripted ground truth.
FR-3: compare simulated sessions with mock sessions recorded under the same conditions.

Ground-truth assumption (SRS_AUDIT A-19): scripts give interval truth only. Inside a scripted interval of type T
the corresponding condition is present; outside every scripted interval the candidate is assumed alone, without
a phone or notes, on the exam tab. This biases false-positive estimates upwards (the safe direction).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml
from scipy.stats import ks_2samp

from riskfusion.features.engine import build_grid, session_features

# detector (simulator config key) -> (grid signal, violation type whose intervals mark the true condition)
DETECTOR_MAP = {
    "phone": ("phone", "PHONE_USE"),
    "face_count_gt1": ("multi_face", "SECOND_PERSON"),
    "person_count_gt1": ("extra_person", "SECOND_PERSON"),
    "identity_mismatch": ("id_mismatch", "IMPERSONATION"),
    "tab_hidden": ("tab_hidden", "TAB_SWITCH"),
    "second_voice": ("foreign", "REMOTE_ASSISTANCE"),
    "book_paper": ("paper", "NOTE_READING"),
}
MIN_SESSIONS = 20  # below this, measured rates are reported but not written to a simulator config


def _truth_mask(T: int, intervals: list[dict[str, Any]], vtype: str | None) -> np.ndarray:
    m = np.zeros(T, dtype=bool)
    for iv in intervals:
        if vtype is None or iv["type"] == vtype:
            m[iv["start_ms"] // 1000 : int(np.ceil(iv["end_ms"] / 1000))] = True
    return m


def measure_detector_errors(sessions: list[dict[str, Any]]) -> dict[str, Any]:
    """sessions: [{"session_id", "duration_s", "events": flat DataFrame, "intervals": [...]}]."""
    acc = {d: {"tp": 0, "fn": 0, "fp": 0, "neg": 0, "sessions_with_truth": 0} for d in DETECTOR_MAP}
    for s in sessions:
        grid, _ = build_grid(s["events"], s["duration_s"])
        T = len(grid)
        any_truth = _truth_mask(T, s["intervals"], None)
        for det, (sig, vtype) in DETECTOR_MAP.items():
            x = grid[sig].to_numpy(dtype=float)
            obs = np.isfinite(x)
            hit = np.nan_to_num(x) > 0.5
            truth = _truth_mask(T, s["intervals"], vtype)
            a = acc[det]
            if truth.any():
                a["sessions_with_truth"] += 1
            a["tp"] += int((hit & truth & obs).sum())
            a["fn"] += int((~hit & truth & obs).sum())
            clean = ~any_truth & obs
            a["fp"] += int((hit & clean).sum())
            a["neg"] += int(clean.sum())
    out = {}
    for det, a in acc.items():
        pos = a["tp"] + a["fn"]
        out[det] = {
            **a,
            "recall": a["tp"] / pos if pos else None,
            "fp_rate_per_second": a["fp"] / a["neg"] if a["neg"] else None,
            "precision_at_observed_prevalence": a["tp"] / (a["tp"] + a["fp"]) if (a["tp"] + a["fp"]) else None,
        }
    return {
        "n_sessions": len(sessions),
        "detectors": out,
        "assumption": __doc__.split("Ground-truth assumption")[1].strip(),
    }


def write_measured_config(measured: dict[str, Any], base_config: Path, out: Path) -> dict[str, Any]:
    """FR-6 output: a new simulator config whose detector rates are the measured ones (where measurable)."""
    cfg = yaml.safe_load(base_config.read_text())
    changes = {}
    if measured["n_sessions"] < MIN_SESSIONS:
        return {"written": False, "reason": f"only {measured['n_sessions']} sessions; need {MIN_SESSIONS}"}
    for det, m in measured["detectors"].items():
        d = cfg["detectors"][det]
        if m["recall"] is not None and m["sessions_with_truth"] >= 3:
            d["recall"] = round(float(np.clip(m["recall"], 0.05, 0.999)), 3)
            changes[det] = {"recall": d["recall"]}
        if m["fp_rate_per_second"] is not None and m["neg"] >= 3600:
            # invert fp_rate = pessimism * ref_prev * recall * (1 - p) / p for the precision p
            k = m["fp_rate_per_second"] / (cfg["pessimism"] * d["ref_prevalence"] * max(d["recall"], 1e-3))
            d["precision"] = round(float(np.clip(1 / (1 + k), 0.05, 1.0)), 3)
            d.pop("assumed", None)
            changes.setdefault(det, {})["precision"] = d["precision"]
    cfg["config_version"] = cfg["config_version"] + "-measured"
    cfg["noise_source"] = f"measured on {measured['n_sessions']} consented mock sessions (FR-6)"
    out.write_text(
        "# Generated by `riskfusion validate-mock` (FR-6). Do not edit by hand.\n"
        + yaml.safe_dump(cfg, sort_keys=False)
    )
    return {"written": True, "path": str(out), "changes": changes}


def compare_distributions(sim: pd.DataFrame, mock: pd.DataFrame, features: list[str]) -> dict[str, Any]:
    """FR-3: two-sample KS test per session feature, simulated vs mock (same conditions)."""
    rows: list[dict[str, Any]] = []
    for f in features:
        a, b = sim[f].dropna().to_numpy(), mock[f].dropna().to_numpy()
        if len(a) < 5 or len(b) < 5:
            continue
        r = ks_2samp(a, b)
        rows.append(
            {
                "feature": f,
                "ks": float(r.statistic),
                "p_value": float(r.pvalue),
                "sim_mean": float(a.mean()),
                "mock_mean": float(b.mean()),
            }
        )
    rows.sort(key=lambda r: -r["ks"])
    n_diff = sum(r["p_value"] < 0.01 for r in rows)
    return {
        "n_features_compared": len(rows),
        "n_significantly_different": n_diff,
        "most_different": rows[:15],
        "n_mock_sessions": int(len(mock)),
        "n_sim_sessions": int(len(sim)),
    }


def mock_session_features(sessions: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for s in sessions:
        grid, obs = build_grid(s["events"], s["duration_s"])
        rows.append({"session_id": s["session_id"], **session_features(grid, obs, s["duration_s"])})
    return pd.DataFrame(rows).set_index("session_id") if rows else pd.DataFrame()


def validate_mock_corpus(
    sessions: list[dict[str, Any]], data_root: Path, sim_dataset: str, base_config: Path, out_dir: Path
) -> dict[str, Any]:
    from riskfusion.features.engine import FEATURE_VERSION

    out_dir.mkdir(parents=True, exist_ok=True)
    measured = measure_detector_errors(sessions)
    cfg_result = write_measured_config(measured, base_config, base_config.with_name("v2_measured.yaml"))
    sim_path = data_root / "features" / FEATURE_VERSION / sim_dataset / "features.parquet"
    mock = mock_session_features(sessions)
    if not sim_path.exists():
        comparison: dict[str, Any] = {"skipped": f"simulated feature store {sim_dataset} not found"}
    else:
        sim = pd.read_parquet(sim_path)
        feats = [c for c in mock.columns if c in sim.columns and "__" in c][:120]
        comparison = compare_distributions(sim, mock, feats)
    report = {"detector_errors": measured, "measured_config": cfg_result, "simulator_vs_mock": comparison}
    (out_dir / "mock_validation.json").write_text(json.dumps(report, indent=2, default=float) + "\n")
    return report
